name:                NBAelimination
version:             0.1.0.0
github:              "https://github.com/Pomona-College-CS181-SP2020/NBAelimination.git"
license:             BSD3
author:              "Alon Lapid"
maintainer:          "alig2015@MyMail.pomona.edu"
copyright:           "2020 Alon Lapid"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            From a list of played games and a list of not yet played games compute which teams can't finish first in thier conference.
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/NBAelimination#readme>

dependencies:
- base >= 4.7 && < 5



library:
  dependencies:
  - base
  - time
  - split
  - sort 
  - containers 
 
  source-dirs: src

executables:
  NBAelimination-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - NBAelimination   
    - time
    - split 
    - directory
  


tests:
  NBAelimination-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - time
    - split 
    - directory
    - NBAelimination

